---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах

implicit:
  - На сайте необходима процедура регистрации с указанием контактных данных
  - Пользователь должен иметь возможность изменять количество товаров в корзине
  - Пользователь должен иметь возможность выбора валют
  - Подтверждение заказа #после нажатия кнопки "Оформить заказ" необходима кнопка "Вы уверены, что готовы сделать заказ?"
  - Пользователь должен иметь возможность сбросить все фильтры без перезагрузки сайта
  - Пользователь должен иметь возможность фильтра товаров по цену (по убыванию, возрастанию), по размеру скидки
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы #требование корректно?
  - Сайт должен быть способен обрабатывать большое количество трафика #требование корректно?
